title: What the fuck is this the site title?
description: This is my site's description.
locale: en_CA
baseurl: "/drbproductions_jekyll"
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - node-modules
  - source
  - config.codekit3
  - package-lock.json
  - package.json
